---
version: "3.7"
services:
    node:
        image: node:12-alpine
        command: sh -c "npm install && npm start"
        ports:
        - 3000:3000
        working_dir: /app
        volumes:
        - ./frontend:/app

    web:
        build:
            context: .
            dockerfile: ./compose/flask/Dockerfile
        ports:
            - "5000:5000"
        working_dir: /app
        volumes: 
            - ./:/app
